#!/bin/env php
<?php
require __DIR__ . '/Config.php';
NoFramework\Config::shell(__FILE__, __COMPILER_HALT_OFFSET__)->start();

__halt_compiler();

ini_set: !ini_set
  opcache.revalidate_freq: 0
  date.timezone: UTC

autoload: !autoload
  - NoFramework
  - namespace: ApiClient
    path: /home/natly.ru/classes/ApiClient
error_handler: !error_handler
class: NoFramework\Shell
log: !new Log\Output
mon: !new
  class: Storage\Mongo
  database: test
mem: !new
  class: Storage\Memory
  data:
    user:
      - name: whiletrue
        password: 123
      - name: exilibris
        password: 345
      - name: nat
        password: 567
m: !new
  class: Model
  storage: !reuse mon
  auto: true

m1: !new
  class: Model
  storage: !reuse mem
  auto: true

vk: !new
  class: \ApiClient\Vk
  cookie_file: !local_path vk_cookie.txt
prompt: '>'
history_path: !local_path .NoFramework_history
shortcuts:
  - from: '`'
    to: '$this->'

  - from: '`{'
    to: 'function () {'

  - from: '`('
    to: '$this('

  - from: '``('
    to: '$this->newInstance('

  - from: '#`(\d+)#'
    to: 'func_get_arg(\1)'

  - from: '#(.+)>$#'
    to: 'return \1'
